In [2]:
import numpy as np

### Soal no 1

In [1]:
start = int(input("Mulai : "))
end = int(input("selesai: "))

print("Mulai:", start)
print("Selesai", end)

array = np.arange(start, end)
print(array)

array_2d = array.reshape(3,9)
print("array_2dimensi", array_2d)

array_3d = array.reshape(9,3)
print("array_3dimensi",array_3d)

Mulai: 1
Selesai 50


NameError: name 'np' is not defined

### Soal no 2

In [4]:
Banyak_data = int(input("Banyak data : "))
start = int(input("Mulai : "))
end = int(input("selesai: "))

print("Banyak data:", Banyak_data)
print("Mulai:", start)
print("Selesai", end)

array = np.random.randint(start, end, Banyak_data)
print(array)
    
array_2d = array.reshape(4,4)

print("array 2 dimensi:", array_2d)

array_transpose = np.transpose(array_2d)
print("array transpose:", array_transpose)

Banyak data: 16
Mulai: 1
Selesai 50
[24 12 40 37  8 15 39  6 15 33  9 47 47  7 47 10]
array 2 dimensi: [[24 12 40 37]
 [ 8 15 39  6]
 [15 33  9 47]
 [47  7 47 10]]
array transpose: [[24  8 15 47]
 [12 15 33  7]
 [40 39  9 47]
 [37  6 47 10]]
