In [2]:
import numpy as np

In [3]:
a = np.array([[2, 3, 5], [6, 7, 10], [12, 13, 15]])
print(a)

[[ 2  3  5]
 [ 6  7 10]
 [12 13 15]]


In [7]:
b = np.array([[2, 3, 5],
            [6, 7, 10], 
            [12, 13, 15]]
)

In [8]:
print(b)

[[ 2  3  5]
 [ 6  7 10]
 [12 13 15]]


In [89]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
d = np.empty(5)
print(d)
np.sort(d)

[2.12199579e-314 1.18407365e-311 4.98018171e-321 6.95293224e-310
 1.69119330e-306]


array([4.98018171e-321, 2.12199579e-314, 1.18407365e-311, 6.95293224e-310,
       1.69119330e-306])

In [17]:
print(np.arange(0, 10, 5))

[0 5]


In [18]:
data= np.arange(0, 100, 10)
np.sort(data)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
np.delete(data, 3)

array([ 0, 10, 20, 40, 50, 60, 70, 80, 90])

In [26]:
example = np.array([[[3, 5, 7],
                     [4, 6, 8]],
                     [[0, 1, 2],
                     [11, 12, 13]],
                     [[15, 16, 17],
                      [25, 21, 22]]])
print(example)

[[[ 3  5  7]
  [ 4  6  8]]

 [[ 0  1  2]
  [11 12 13]]

 [[15 16 17]
  [25 21 22]]]


In [27]:
np.sort(example)

array([[[ 3,  5,  7],
        [ 4,  6,  8]],

       [[ 0,  1,  2],
        [11, 12, 13]],

       [[15, 16, 17],
        [21, 22, 25]]])

In [31]:
new_example = np.delete(example, 0)
new_example

array([ 5,  7,  4,  6,  8,  0,  1,  2, 11, 12, 13, 15, 16, 17, 25, 21, 22])

In [36]:
new_example.ndim

1

In [40]:
t = np.append(new_example, [3])

In [45]:
t.reshape(3, 6)

array([[ 5,  7,  4,  6,  8,  0],
       [ 1,  2, 11, 12, 13, 15],
       [16, 17, 25, 21, 22,  3]])

In [46]:
type(a)

numpy.ndarray

In [47]:
a = np.array([[2, 3, 5], [6, 7, 10], [12, 13, 15]])
print(a)

[[ 2  3  5]
 [ 6  7 10]
 [12 13 15]]


In [48]:
print(a[a>=10])

[10 12 13 15]


In [52]:
test = (a >= 5)
print(a[test])

[ 5  6  7 10 12 13 15]


In [54]:
np.sort(a)

array([[ 2,  3,  5],
       [ 6,  7, 10],
       [12, 13, 15]])

In [61]:
a = np.array([[2, 3, 5], [6, 7, 10], [12, 13, 15]])
print(a[0:3, 1])

[ 3  7 13]


In [65]:
data = np.random.random((3,5))
print(data)

[[0.97924805 0.51220965 0.41709989 0.96259436 0.96232709]
 [0.47333695 0.81661038 0.62548521 0.87435094 0.39332889]
 [0.12989285 0.8354263  0.40963516 0.27530679 0.84720008]]


In [66]:
np.sort(data)

array([[0.41709989, 0.51220965, 0.96232709, 0.96259436, 0.97924805],
       [0.39332889, 0.47333695, 0.62548521, 0.81661038, 0.87435094],
       [0.12989285, 0.27530679, 0.40963516, 0.8354263 , 0.84720008]])

In [69]:
print(data.max())

0.97924805128726


In [70]:
print(data.sum())

9.51405259143209


In [71]:
print(data.min())

0.12989284713874272


In [79]:
data = np.random.random((5,5))
print(data)

[[0.1874591  0.72013757 0.29400181 0.62455832 0.43562442]
 [0.08640416 0.99000174 0.49014505 0.53498995 0.3906871 ]
 [0.84562546 0.64500622 0.40606463 0.03793639 0.06883684]
 [0.30703415 0.82594503 0.27757077 0.67127538 0.70051954]
 [0.23383788 0.83515127 0.48464557 0.67911855 0.56715344]]


In [82]:
data.min(axis=0)

array([0.08640416, 0.64500622, 0.27757077, 0.03793639, 0.06883684])

In [85]:
data.sum(axis=0)

array([1.66036076, 4.01624183, 1.95242783, 2.54787859, 2.16282134])

In [87]:
data.sum()

12.339730344066334